---
params:
    dynamictitle: "Whole Exome Seq. Summary"
    reportdate: !r Sys.Date()
output: 
        html_notebook:
#         html_document:
         toc: true
         toc_float: true
         depth: 3
#         number_section: true
#         theme: readable
         theme: united
         highlight: tango
#         fig_caption: true
#         df_print: paged
#         df_print: tibble
#         df_print: kable
         fig_caption: yes 
         fig_retina: 1 
#         code_download: false
         
#kable
title: "`r params$dynamictitle`"
#date: "`r params$reportdate`"
author: Park MinYoung(minmin@dnalink.com) in BI, DNA Link
    
---

***

```{r setting, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, fig.width=7)
options(DT.options = list(pageLength = 10, language = list(search = 'Filter:')))
#setwd("/home/adminrig/workspace.min/HiSeq_vs_NovaSeq")
source("/home/adminrig/src/short_read_assembly/bin/R/Min.R")
```

```{r library, include=FALSE}
library(pacman)
p_load(ggplot2, tidyr, dplyr, DT, scales, tibble, mosaic, UpSetR, purrr, readr, ggrepel, ggpubr)

library(DataExplorer)

library(knitr)
library(kableExtra)
options(knitr.table.format = "html") 


# data_status()
# pkg_clean()
# rm(list=ls())
# http://rstudio.github.io/DT/extensions.html
```





```{r, include=FALSE}
#df <- read_tsv("NA12878/Summary.txt")
df <- read_tsv("Summary.txt")
```

```{r, include=FALSE}
plot_str(df)
```

```{r, include=FALSE}
names(df)
```

```{r data sort by sample raw}
names(df)[4]="Aligned.Rate"
names(df)[11]="Duplicate.Rate"
depths = paste0("DP", names(df)[c(18:25)])
names(df)[c(18:25)] <- depths

names(df)[44]="Ti_Tv"

sample_order <- df[order(df$Raw),c(1,2,3,13)]$Sample 
df$Sample <- factor( df$Sample, levels = sample_order, ordered =TRUE) 
  
```

```{r function1}
value_down <- function(value,percent=10){
  return( min(value) - min(value)*percent/100  )
}

value_up <- function(value,percent=10){
  return( min(value) + min(value)*percent/100  )
}

```


```{r function2}

conc_fill <- function(conc){
  
  samples =unique(c(conc$A,conc$B))
  identity <- 
    data.frame(A = samples,
               B = samples,
               Overlapping_calls = 0, 
               Nonmissing_calls=0, 
               Conc_Num=0,
               ConcordantRate=100, 
               stringsAsFactors = FALSE) 

  conc <-
    conc %>% 
    mutate(C=A, A=B, B=C) %>% 
    select(-C) %>% 
    bind_rows(., conc) %>% 
    bind_rows(., identity)
  
}

conc_plot <- function(conc){

  conc %>% 
    ggplot( aes(A, B, fill=ConcordantRate)) + 
    theme_bw() +
    geom_tile(col="grey") + 
    scale_fill_gradientn(colours=rev(cols)) + 
    geom_text(aes(label=ConcordantRate), col="darkblue", size=4) + 
    theme(axis.text.x = element_text(angle=90),
          legend.position = "bottom")
    
}

FunctionDump("conc_plot")
FunctionDump("conc_fill")

```


<br>

# Analysis Result

<br>

```{r}
type_list =c("Sample", "Raw", "Aligned.Rate", "Duplicate.Rate", "OnTargetRate", "MeanDP", "nVariantLoci", "nHets", "nHomVar", "hetHomRatio", "Ti_Tv")

df_step1<-
  df %>% 
  #select(Sample, Raw, Aligned.Rate, Duplicate.Rate, OnTargetRate, MeanDP, nVariantLoci, nHets, nHomVar, hetHomRatio, Ti_Tv) %>% 
  select_(.dots = type_list) %>% 
  gather("Type", "value", -1) %>%
  mutate(Type = factor(Type, levels = type_list, ordered = TRUE)) 

```


```{r main, fig.height=12, fig.width=10, fig.cap= "Analysis Summary"}

ggplot(df_step1,  aes( Sample, value)) + 
  geom_line( aes(group=Type), alpha=.1 ) +
  geom_point(aes(col=Sample), size=2, shape=21, stroke=2) + 
  facet_grid(Type~., scales = "free") + 
  theme(axis.text.x = element_text(angle=90),
        strip.text = element_text( size = 10 , colour = "darkblue", face = "bold"))

```


<br>

```{r}
show_datatable(df, "summary")

```


<br>

# Raw seq. vs. Aligned rate

<br>

```{r raw_seq vs. aligned rate}
y_min <- value_down(df$Aligned.Rate, 20)
ggplot(df, aes(Raw, Aligned.Rate)) + 
  geom_point( col="lightblue", shape=21, stroke=3, size=1  ) +
  scale_x_continuous( label = unit_format(unit="G", scale=1e-9, digits=2)) + 
  lims( y=c(y_min,100) ) + 
  geom_label_repel( aes(label=Sample), size=3, point.padding = 0.5, box.padding = 3)#, force = 5)
  #geom_text_repel( aes(label=Sample), size=3, point.padding = 0.5, box.padding = 3)#, force = 5)
```


<br>

# Duplicate Rate

<br>

```{r}
#options(scipen = 0)
#Dup.cor <- cor.test(df$Raw, df$Duplicate.Rate)
#paste(round(Dup.cor$estimate,4),Dup.cor$p.value , sep=" ")

# ggplot(df, aes(Raw, Duplicate.Rate)) + 
#   geom_point( col="lightblue", shape=21, stroke=3, size=1  ) +
#   geom_smooth(method="lm") +
#   scale_x_continuous( label = unit_format(unit="G", scale=1e-9, digits=1)) + 
#   #lims( y=c(y_min,100) ) + 
#   geom_label_repel( aes(label=Sample), size=3, point.padding = 0.5, box.padding = 3)#, force = 5)
#   #geom_text_repel( aes(label=Sample), size=3, point.padding = 0.5, box.padding = 3)#, force = 5)

ggscatter(df, x = "Raw", y = "Duplicate.Rate",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Raw Sequences", ylab = "Duplicates Rate") + 
  scale_x_continuous( label = unit_format(unit="G", scale=1e-9, digits=2)) + 
  geom_label_repel( aes(label=Sample), size=3, point.padding = 0.5, box.padding = 3)#, force = 5)


```


<br>

# Depth Coverage

<br>
```{r}

cols = colorRampPalette( RColorBrewer::brewer.pal(9,"RdYlBu") )( 30 )

#RColorBrewer::display.brewer.all()

df_step2<-
  df %>% 
  select_(  .dots= c("Sample", depths) ) %>% 
  #select(Sample, DP1, DP5, DP10, DP15, DP20, DP25, DP30, DP50)
  gather("Depth", "Value", -1) %>% 
  mutate( Depth = factor( Depth, levels = depths, ordered = TRUE ) ) 

```


```{r, fig.width=18, fig.height=8}

  
depth_plot1<-
  ggplot(df_step2,aes(Depth, Sample, fill=Value)) + 
  geom_tile(col="white") + 
  scale_fill_gradientn(colours=cols) + 
  geom_text(aes(label=Value), size=3)

depth_plot2<-
ggplot(df_step2, aes(Depth, Value, group=Sample,col=Sample)) +
  geom_line(alpha=.1) +
  geom_point(alpha=.7, shape=21, size=3) + 
  theme(legend.position = c(0.2, 0.5),
        legend.background = element_rect(fill="white",
                                  size=0.5, linetype="solid", 
                                  colour ="darkblue")
        )
  
 

cowplot::plot_grid(depth_plot1, depth_plot2, labels="AUTO")

```



<br>

# Relationship between Samples

<br>

```{r, include=FALSE}
#conc <- read_tsv("NA12878/ConcordantRate")
conc <- read_tsv("ConcordantRate")
conc$A<-as.character(conc$A)
conc$B<-as.character(conc$B)
conc
```

<br>

## Relationship Analysis

<br>

```{r}
filename_dt="ConcRate"
datatable(conc,
          extensions = c('Scroller', 'Buttons'),
          options = list(
          #autoWidth = TRUE,
          deferRender = TRUE,
          scrollX = TRUE,
          scrollY = 200,
          scroller = TRUE,
          dom = 'Bfrtip',
          buttons = list('copy',
                     list(extend='excel',filename=filename_dt),
                     list(extend='csv',filename=filename_dt)),
          lengthMenu = c( 10, 15, 20, 100),
          columnDefs = list(list(width = '1000px', targets = "_all", className = 'dt-center')
            )

          )
)
```


```{r, include=FALSE}


conc %>% 
  group_by(A) %>% 
  nest() %>% 
  mutate( n = map_dbl(data, ~.x %>% NROW ) )

conc %>% 
  split(.$A)
#  group_by(A) %>% 
#  nest() 
  
conc
```

<br>

## Concordance Matrix

<br>


```{r, fig.width=10, fig.height=11}
#?ggplot2::theme_set()
conc<-conc_fill(conc)
conc_plot(conc)
```



```{r}
high<-
conc %>% 
  filter(ConcordantRate > 90, ConcordantRate <100 )
  #filter( ConcordantRate >1000 )

```

<br>

## Related Samples

<br>

```{r, result="asis"}

if(NROW(high) > 0) {
  filename_dt="HighConc"
  datatable(high,
          extensions = c('Scroller', 'Buttons'),
          options = list(
          #autoWidth = TRUE,
          deferRender = TRUE,
          scrollX = TRUE,
          scrollY = 200,
          scroller = TRUE,
          dom = 'Bfrtip',
          buttons = list('copy',
                     list(extend='excel',filename=filename_dt),
                     list(extend='csv',filename=filename_dt)),
          lengthMenu = c( 10, 15, 20, 100),
          columnDefs = list(list(width = '1000px', targets = "_all", className = 'dt-center')
            )

          )
)
}else{
  cat("**There are not related samples**")
}
   
```


