#cutadapt -f fastq -e 0.05			\
cutadapt -f fastq -e 0.02			\
-O 38						\
--match-read-wildcards				\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAAT	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATC	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGA	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAG	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTT	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTAC	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTA	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAA	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCC	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCA	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCC	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGC	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAA	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCC	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCG	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACG	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGTGG	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGAT	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCT	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACG	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGT	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGC	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCA	\
-b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTG	\
$1 -o $1.cutadapt.index.fastq >& $1.log
