#!/bin/bash
. ~/.bash_function

DB=${HOME}/bin/mark.db


case $1 in

        show)
#                       cat -n $DB
                        cat -n $DB | sed 's/^ \+//g;s/( )/()/g'|  awk -F'\t' '{printf "%+2s\t%-22s\t%-60s\t%-30s\n", $1, $2, $3, $4}'
                        ;;

        cd)
                        DIR=$(cut -f2 $DB | sed -n "$2"p) 
                        echo "Go to $DIR"
                        cd $DIR && exec bash
                        ;;
        
        edit)
                        vi $DB
                        ;;
        
        rm_dup)
                        
                        echo "Removal Redundant Directories"
                        \mv -f $DB $DB.bak
                        UniqueLine.sh $DB.bak 2 > $DB
                        ;;      
        
        del)

                        echo "Removal Line : $2"
                        sed -n "$2p" $DB
                        sed -i.bak "$2d" $DB
                        ;;

        back)

                        echo "deletion back"
                        if [ -f "$DB.bak" ];then
                                \mv -f $DB.bak $DB
                        else
                                echo "Nothing Back"
                        fi
                        ;;

        *)
                        echo -e $(date +'%Y-%m-%d %H:%M:%S')"\t"$PWD"\t""$@" >> $DB
                        ;;

esac

