#!/bin/sh

. ~/.bash_function

if [ $# -eq 3 ];then

perl -snle'
if(@ARGV){
	@F=split "\t", $_;
	$h{$F[0]} = $F[2];
}else{
	$c++;
	push @line, $_;

	if( $c%4==0 ){
		$tag = substr $line[1], 0, $len;
		if( $h{$tag} ){
			push @{$fastq{$tag}}, join "\n", @line;
		}else{
			push @{$fastq{Unknown}}, join "\n", @line;
		}
		@line = ();
	}
}

}{ 
	for( keys %fastq){
		open $F, ">$file.$h{$_}.fastq" or "die $!";
		print $F join "\n", @{$fastq{$_}};
		close $F;
	}

' -- -file=$2 -len=$3 $1 $2

# sh TagSplit.sh KJ1_AAAAAA_L001_R1_001.fastq.char5.count.out try.fastq 5

# head KJ1_AAAAAA_L001_R1_001.fastq.char5.count.out
## CACTA	47962	MPS2B.F	CACTAGGATACCAACAAACC	CACTAGGATACCAACAAACC	GAGGATGGTGGTCAAGGGAC
## GTTAT	44100	MPS3B.R	GTTATTATTATGTCCTACAAGC	GCACCCTATGTCGCAGTATCTGTC	GTTATTATTATGTCCTACAAGC
## AAATA	38586	MPS3A.R	AAATAATAGGATGAGGCAGGAATC	GGGAGCTCTCCATGCATTTGG	AAATAATAGGATGAGGCAGGAATC
## GAGGA	37861	MPS2B.R	GAGGATGGTGGTCAAGGGAC	CACTAGGATACCAACAAACC	GAGGATGGTGGTCAAGGGAC
## GCACC	21568	MPS3B.F	GCACCCTATGTCGCAGTATCTGTC	GCACCCTATGTCGCAGTATCTGTC	GTTATTATTATGTCCTACAAGC
## GGGAG	19497	MPS3A.F	GGGAGCTCTCCATGCATTTGG	GGGAGCTCTCCATGCATTTGG	AAATAATAGGATGAGGCAGGAATC
## TCTTT	19208	VR2.F	TCTTTTGGCGGTATGCACTTT	TCTTTTGGCGGTATGCACTTT	GGTGTATTTGGGGTTTGGTTG
## CCCAA	13133	MPS1A.F	CCCAAAGCTAAGATTCTAAT	CCCAAAGCTAAGATTCTAAT	TACTACAGGTGGTCAAGTAT
## TACTA	12757	MPS1A.R	TACTACAGGTGGTCAAGTAT	CCCAAAGCTAAGATTCTAAT	TACTACAGGTGGTCAAGTAT
## TGAGA	8925	MPS5A.R	TGAGATTAGTAGTATGGGAG	TGGCCACAGCACTTAAAC	TGAGATTAGTAGTATGGGAG


# ./TagSplit.cutadapt.sh KJ1_AAAAAA_L001_R1_001.fastq.char5.count.out try.fastq
 TagSplit.cutadapt.sh $1 $2 | sh 

 else
	usage "info XXX.fastq char_len[5]"
fi
