#!/bin/sh

. ~/.bash_function

if [ $# -eq 2 ];then

perl -F'\t' -asnle'
$file = "$fastq.$F[2].fastq";
next if ! -e $file;

$F[2]=~/(\w)$/;
$strand = $1;
if( $strand eq "F" ){
	$prime3 = $F[5];
	$prime3 =~ tr/ACGT/TGCA/;
	$prime3_seq = reverse ($prime3);
	
	$in = $file;
	$fq = "$file.prime3.fastq";

	print "cutadapt -e 0.3 -o $fq -a $prime3_seq -O 10 $in &> $fq.log";

	$prime5_seq = $F[4];

	$in = $fq;
	$fq = "$fq.prime5.fastq";

	print "cutadapt -e 0.3 -o $fq -b $prime5_seq -O 10 $in &> $fq.log";

}else{
	$prime3 = $F[4];
	$prime3 =~ tr/ACGT/TGCA/;
	$prime3_seq = reverse ($prime3);
	
	$in = $file;
	$fq = "$file.prime3.fastq";

	print "cutadapt -e 0.3 -o $fq -a $prime3_seq -O 10 $in &> $fq.log";

	$prime5_seq = $F[5];

	$in = $fq;
	$fq = "$fq.prime5.fastq";

	print "cutadapt -e 0.3 -o $fq -b $prime5_seq -O 10 $in &> $fq.log";
}


' -- -fastq=$2 $1

# '-- -fastq=try.fastq KJ1_AAAAAA_L001_R1_001.fastq.char5.count.out

else
	usage "info xxx.fastq"
fi

## [adminrig@node01 TagSplit]$ sed -n '2~4p'  try.fastq.MPS3A.F.fastq | head
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAATATCTGTCTTTGATTCCTGCCTCATCCTATTATTT
## GGGAGCTCTCCATGCA
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATT
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTT
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTT
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTT
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTT
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCGGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTT
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTT
## GGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTT
## [adminrig@node01 TagSplit]$ grep MPS3A  -A 1 ../*fa
## >chrM:34+159 MPS3A 126bp GGGAGCTCTCCATGCATTTGG AAATAATAGGATGAGGCAGGAATC
## GGGAGCTCTCCATGCATTTGGtattttcgtctggggggtatgcacgcgatagcattgcgagacgctggagccggagcaccctatgtcgcagtatctgtctttGATTCCTGCCTCATCCTATTATTT
## [adminrig@node01 TagSplit]$
## 
## 
## ## reverse
## 
## [adminrig@node01 TagSplit]$  sed -n '2~4p' try.fastq.MPS3A.R.fastq | head | less -S
## AAATAATAGGATGAGGCAGGAATCAAAGACAGATACTGCGACATAGGGTGCTCCGGCTCCAGCGTCTCGCAATGCTATCGCGTGCACACCCCCCAGACGAAAATACCAAATGCATGGAGAGCTCCCGTATACTG
## AAATAATAGGATGAGGCAGGAATCAAAGACAGATACTGCGACATAGGGTGCTCCGGCTCCAGCGTCTCGCAATGCTATCGCGTGCACACCCCCCAGACGAAAATACCAAATGCATGGAGAGCTCCCGTTAAGGGCGGGTAGGTTTGTTGGTATCCTAGTGGGTGAGGGGTGGCTTTGGAGTTGCAGTTGATGTGAGATAGTTTGAGGGTTGATTGCTGTACTTGCTTGTAAGCATGG
## AAATAATAGGATGAGGCAGGAATCAAAGACAGATACTGCGACATAGGGTGCTCCGGCTCCAGCGTCTCGCAATGCTATCGCGTGCACACCCCCCAGACGAAAATACCAAATGCATGGAGAGCTCCCGAGGATGGTGGTCAAGGGACCCCTATCTGAGGGGGGTCATCCATGGGACGAGAAGGGATTTGACTATAATGTGCTATGTACGGTAAATGGCTTTATGTGCTATGTGCTGTT
## AAATAATAGGATGAGGCAGGAATCAAAGACACGATACTGCCGACATAGGGTGCTCCGGCTCCAGCGTCTCGCAATGCTATCGCGTGCACACCCCCCAGACGAAAATACCAAATGCATGGAGAGCTCCCG
## AAATAATAGGATGAGGCAGGAATCAAAGACACGATACTGCCGACATAGGGGTGCCTCCGGCTCCAGCGTCTCGCAATGCTATCGCGTGCACACCCCCCAGACGAAAATACCAAATGCATGGAGAGCTCCCG
## 
## [adminrig@node01 TagSplit]$ grep -A 1 MPS3A ../*fa
## >chrM:34+159 MPS3A 126bp GGGAGCTCTCCATGCATTTGG AAATAATAGGATGAGGCAGGAATC
## GGGAGCTCTCCATGCATTTGGtattttcgtctggggggtatgcacgcgatagcattgcgagacgctggagccggagcaccctatgtcgcagtatctgtctttGATTCCTGCCTCATCCTATTATTT
## 
