
---
params:
    dynamictitle: "VarEval Comparison"
    reportdate: !r Sys.Date()
output: 
        html_notebook:
#         html_document:
         toc: true
         toc_float: true
         depth: 3
#         number_section: true
#         theme: readable
         theme: united
         highlight: tango
#         fig_caption: true
#         df_print: paged
#         df_print: tibble
#         df_print: kable
#         fig_caption: yes 
#         fig_retina: 1 
#         code_download: false
         
#kable
title: "`r params$dynamictitle`"
#date: "`r params$reportdate`"
author: Park MinYoung(minmin@dnalink.com) in BI, DNA Link
    
---

***

```{r setting, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, fig.width=7)
options(DT.options = list(pageLength = 10, language = list(search = 'Filter:')))
#setwd("/home/adminrig/workspace.min/HiSeq_vs_NovaSeq")
source("/home/adminrig/src/short_read_assembly/bin/R/Min.R")
```

```{r library, include=FALSE}
library(pacman)
p_load(ggplot2, tidyr, dplyr, DT, scales, tibble, mosaic, UpSetR, purrr, readr)

library(ggrepel)
library(knitr)
library(kableExtra)
options(knitr.table.format = "html") 


# data_status()
# pkg_clean()
# rm(list=ls())
# http://rstudio.github.io/DT/extensions.html
```

```{r, include=FALSE}
df <- read_tsv("VarEval")

vartype = c("nSNPs", "nInsertions", "nDeletions")
het_hom <- c("nHets", "nHomVar")

```

GATK3 의 Variant Eval 의 결과를 각 Analysis 에 따라서 비교 정리 한 결과   

<br>

# Variant Eval Summary

<br>

```{r}
filename_dt="summary"
datatable(df,
          extensions = c('Scroller', 'Buttons'),
          options = list(
          #autoWidth = TRUE,
          deferRender = TRUE,
          scrollX = TRUE,
          scrollY = 200,
          scroller = TRUE,
          dom = 'Bfrtip',
          buttons = list('copy',
                     list(extend='excel',filename=filename_dt),
                     list(extend='csv',filename=filename_dt)),
          lengthMenu = c( 10, 15, 20, 100),
          columnDefs = list(list(width = '1000px', targets = "_all", className = 'dt-center')
            )

          )
)

```

<br>

# nVariants & hetHomRatio

<br>


```{r, fig.width=10, fig.height=6}
df %>% 
  ggplot( aes(Sample, nVariantLoci, group=LABEL, col=LABEL)) + 
  geom_point() + 
  geom_line() + 
  geom_text(aes(label=hetHomRatio),size=4, vjust=-1) + 
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "top") + 
  scale_color_discrete(name="Analysis") + 
  scale_y_continuous(label=unit_format(unit="K", scale=1e-3, digits=1))
```

<br>

# VarType Count

<br>

```{r, fig.width=10, fig.height=6}

df %>% 
  select_(.dots=c("Sample","LABEL", vartype)) %>% 
  gather("VarType", "Count", -(1:2)) %>% 
  ggplot( aes(Sample, Count, fill=VarType )) +
  geom_bar(stat="identity") + 
  facet_grid(.~LABEL) + 
  scale_color_discrete(name="Analysis") + 
  scale_y_continuous(label=unit_format(unit="K", scale=1e-3, digits=1)) + 
  theme(legend.position = "top") + 
  coord_flip()
  
```

<br>

# Het / Hom Count

<br>

```{r, fig.width=10, fig.height=6}
HetHom<-
df %>% 
  select_(.dots=c("Sample","LABEL", het_hom, "hetHomRatio" )) %>% 
  gather("VarType", "Count", -(1:2)) 

filter(HetHom, VarType %in% het_hom) %>% 
  #forcats::fct_drop(VarType) %>% 
  ggplot( aes(Sample, Count, fill=forcats::fct_rev(VarType) )) +
  geom_bar(stat="identity") + 
  #geom_text(data=filter(HetHom, VarType == "hetHomRatio") %>% droplevels(), aes(label=Count)) +
  facet_grid(.~LABEL, scales="free") + 
  scale_fill_discrete(name="Analysis") + 
  scale_y_continuous(label=unit_format(unit="K", scale=1e-3, digits=1)) + 
  theme(legend.position = "top") + 
  coord_flip()

```

