---
title: "HLA Analysis"
author: "minmin"
date: '2016 11 2 '
output: html_document
---

```{r setup, include=FALSE}

setwd("/home/adminrig/workspace.min/HLA.Analysis/KNIH.35K/HLA/Analysis/KORV1_0-v1")
library(pacman)
#p_load(dplyr, ggplot2, tidyr, gridExtra, plotly, scales)
p_load(dplyr, ggplot2, scales, printr, xtable, knitr, plotly, tidyr, gridExtra)

#files <- list.files(pattern = "^HLA_4dig")
#filenames <- Sys.glob("*.dbf")
#files <- list.files()
#dbf.files <- files[-grep(".xml", files, fixed=T)]

#plot_list=list()

knitr::opts_chunk$set(echo = TRUE)
```

## HLA Analysis


```{r pressure, echo=FALSE}

#i=files[1]
#for (i in files) {
  #print(i)
  #gene<-sub("HLA_4dig_(.+).txt", "\\1", i, perl=TRUE)
  #print(gene)

#gene<-sub("HLA_4dig_(.+).txt", "\\1", files[1],perl=TRUE)


df<-read.table( "HLA_4dig.AnalysisResult", header =T, sep="\t", colClasses=c("character", "factor", "numeric", "factor", "numeric", "factor", "numeric", "factor"))
#head(df)
#str(df)



ggplot(df, aes(AB)) + 
  geom_bar() + 
  facet_wrap( ~LABEL, ncol=1, scales="free")

#http://stackoverflow.com/questions/24576515/relative-frequencies-proportions-with-dplyr
# mtcars %>%
#   count(am, gear) %>%
#   mutate(freq = n / sum(n)) %>%
#   ungroup()


top_allele<-
  df %>%
  count(LABEL, AB) %>%
  mutate(percent = n/sum(n) * 100) %>%
  top_n(n=20, wt=percent) %>%
  ungroup() 
  #arrange(desc(n) ) %>%
  #head(1000) %>%
  #View()
  

ggplotly(
  ggplot(top_allele, aes(reorder(AB, n), percent, fill=AB)) + 
  geom_bar(stat="identity") + 
  #geom_text( aes(y=percent, label=comma(sprintf("%1.2f%%", percent))), colour="blue") +
  #annotate("text", x=-Inf, y=Inf, label=paste0("Discovered types : ", length(unique(df$AB))), size=4, hjust=-0.1, vjust=1, colour="red") + 
  theme(legend.position="none") +
  labs(title = "HLA Genes", x="HLA Type", y="Percent (%)") + 
  facet_wrap( ~ LABEL, ncol=1, scales="free")
)

dff<-
df %>%
  select(probeset_id, LABEL, X1, X2) %>%
  gather( "allele", "type", 5:6 ) 
#head(dff)
#head(df)

top<-
dff %>%
  group_by(type) %>%
  summarise(n = n()) %>%
  mutate(percent = n/sum(n) * 100) %>%
  arrange(desc(n) ) %>%
  head(20)

B<-ggplotly(
  ggplot(top, aes(reorder(type, n), percent, fill=type)) + 
  geom_bar(stat="identity") + 
  geom_text( aes(y=percent, label=comma(sprintf("%1.2f%%", percent))), colour="blue") +
  annotate("text", x=-Inf, y=Inf, label=paste0("Discovered types : ", length(unique(dff$type))), size=4, hjust=-0.1, vjust=1, colour="red") + 
  theme(legend.position="none") +
  labs(title = title_str, x="HLA Type", y="Percent (%)")
)

l<-list(A,B)

do.call(grid.arrange, c(l, list(ncol=1) ) )

# 
# png("HLA.gene.png", width=1200, height=4400)
# http://stackoverflow.com/questions/20531579/plotting-multiple-graphs-in-r-ggplot2-and-saving-the-result
# 
#do.call(grid.arrange, c(plot_list, list(ncol=1) ) )
 

#}


```
