---
title: "R Notebook"
output: html_notebook
---

***

http://stackoverflow.com/questions/25314336/how-to-extract-the-maximum-value-within-each-group-in-a-data-frame

```{r}

df <- read.table(header = TRUE, text = 'Gene   Value
A      12
A      10
B      3
B      5
B      6
C      1
D      3
D      4')

df

```
```{r, collapse=TRUE}
# aggregate
aggregate(df$Value, by = list(df$Gene), max)
aggregate(Value ~ Gene, data = df, max)

```
```{r}
# tapply
tapply(df$Value, df$Gene, max)

```

```{r}
# split + lapply
lapply(split(df, df$Gene), function(y) max(y$Value))


```
```{r}

# plyr
require(plyr)
ddply(df, .(Gene), summarise, Value = max(Value))


```
```{r}
# dplyr
require(dplyr)
df %>% 
  group_by(Gene) %>% 
  summarise(Value = max(Value), sum=sum(Value))

```
```{r}

# data.table
require(data.table)
dt <- data.table(df)
dt[ , max(Value), by = Gene]

```
```{r}

# doBy
require(doBy)
p_load(doBy)
summaryBy(Value~Gene, data = df, FUN = max)

```

```{r}


# sqldf
require(sqldf)
sqldf("select Gene, max(Value) as Value from df group by Gene", drv = 'SQLite')

# ave
df[as.logical(ave(df$Value, df$Gene, FUN = function(x) x == max(x))),]

```
