.mode tabs
.headers on

CREATE TABLE NGS(
"ServiceID" VARCHAR(255) NOT NULL,
"ServiceType" VARCHAR(20),
"KitType" VARCHAR(10),
"SampleID" VARCHAR(25),
"Raw" INTEGER,
"Aligned" INTEGER,
"TargetAligned" INTEGER,
"OffTarget" INTEGER,
"Unaligned" INTEGER,
"TotalReads" INTEGER,
"TotalReadsAligned" INTEGER,
"AlignedPercent" REAL,
"UnpairedReadsAligned" INTEGER,
"PairedReadsAligned" INTEGER,
"UnalignedReads" INTEGER,
"DuplicateUnpairedReads" INTEGER,
"DuplicatePairedReads" INTEGER,
"OpticalDuplicatePairedReads" INTEGER,
"DuplicateRateOfAligned" REAL,
"EstimatedLibrarySize" INTEGER,
"MeanDepth" REAL,
"nVariantLoci" INTEGER,
"variantRate" REAL,
"nSNPs" INTEGER,
"nMNPs" INTEGER,
"nInsertions" INTEGER,
"nDeletions" INTEGER,
"nComplex" INTEGER,
"nSymbolic" INTEGER,
"nMixed" INTEGER,
"nNoCalls" INTEGER,
"nHets" INTEGER,
"nHomRef" INTEGER,
"nHomVar" INTEGER,
"nSingletons" INTEGER,
"nHomDerived" INTEGER,
"heterozygosity" REAL,
"heterozygosityPerBp" REAL,
"hetHomRatio" REAL,
"indelRate" REAL,
"indelRatePerBp" REAL,
"insertionDeletionRatio" REAL,
"key" VARCHAR(255) primary key, 
"timestamp" TIMESTAMP NOT NULL DEFAULT current_timestamp
);

