create table KORV1_1(
"probeset_id" VARCHAR(255) NOT NULL,
"create_date" VARCHAR(255),
"grid_status" VARCHAR(255),
"serial_num" VARCHAR(10),
"barcode" VARCHAR(50),
"well" NCHAR(3) NOT NULL,
"scanner" NCHAR(3) NOT NULL,
"hyb_start_time" VARCHAR(255),
"hyb_stop_time" VARCHAR(255),
"hyb_fluidics_time" VARCHAR(255),
"access_time" VARCHAR(255),
"md5sum" VARCHAR(255) not null,
"celname" VARCHAR(255) NOT NULL,
"id" VARCHAR(255) NOT NULL,
"set" NCHAR(8) NOT NULL,
"well2" NCHAR(3) NOT NULL,
"axiom_dishqc_DQC" REAL,
"apt_geno_qc_gender" VARCHAR(20) NOT NULL,
"apt_probeset_genotype_gender" VARCHAR(20) NOT NULL, 
"call_rate" REAL,
"het_rate" REAL,
"cn-probe-chrXY-ratio_gender_meanX" REAL,
"cn-probe-chrXY-ratio_gender_meanY" REAL,
"cn-probe-chrXY-ratio_gender_ratio" REAL,
"key" VARCHAR(255) primary key, 
"timestamp" TIMESTAMP NOT NULL DEFAULT current_timestamp);

